name 'demo_book'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures demo_book'
long_description 'Installs/Configures demo_book'
version '0.1.0'
